version: '3.7'
services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    volumes:
      - './db/:/data/db'
  api:
    image: strapi/strapi:3.0.0-beta.17.5
    environment:
      - APP_NAME=api
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - NODE_ENV=production
    volumes:
      - './api:/srv/app'
    links:
      - 'db:mongo'
    ports:
      - '1337:1337'
    depends_on:
      - db
volumes:
  db:
  api: